# Generated by Django 6.0.4 on 2026-04-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'colleges',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='import_source',
            field=models.CharField(blank=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='is_cross_cutting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetablesession',
            name='lecturer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='course_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='timetable.college')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('BSC', 'Bachelor'), ('MSC', 'Masters')], default='BSC', max_length=10)),
                ('uqf_level', models.PositiveSmallIntegerField(default=8)),
                ('duration_years', models.PositiveSmallIntegerField(default=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='timetable.department')),
            ],
            options={
                'db_table': 'programs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='timetablesession',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='timetable.program'),
        ),
        migrations.CreateModel(
            name='TimetableImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('sessions_created', models.IntegerField(default=0)),
                ('sessions_skipped', models.IntegerField(default=0)),
                ('venues_created', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.academicperiod')),
            ],
            options={
                'db_table': 'import_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
