# Generated by Django 6.0.4 on 2026-04-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('venue_type', models.CharField(choices=[('LECTURE_HALL', 'Lecture Hall'), ('LAB', 'Laboratory'), ('SEMINAR_ROOM', 'Seminar Room'), ('WORKSHOP', 'Workshop')], default='LECTURE_HALL', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='venues.building')),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['building__name', 'name'],
                'unique_together': {('building', 'name')},
            },
        ),
    ]
