# Generated by Django 6.0.4 on 2026-04-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['code']},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='venue',
            name='wing',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('LECTURE_HALL', 'Lecture Hall'), ('LAB', 'Laboratory'), ('SEMINAR_ROOM', 'Seminar Room'), ('THEATRE', 'Theatre'), ('LIBRARY', 'Library Room'), ('OTHER', 'Other')], default='LECTURE_HALL', max_length=20),
        ),
        migrations.RemoveField(
            model_name='venue',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='has_projector',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='has_whiteboard',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='notes',
        ),
    ]
